### ISSUE TITLE
Synchronisation should not change visibility status

### ISSUE THREAD

**Issue by stefandivora** [CTFd/ctfcli#11]
When updating challenges with the cli tool, the challenges are set to state "visible", regardless of their previous state.

Expected behavior:
Challenge visibility state stays hidden when being hidden beforehand.

Actual behavior:
Challenge is set to "visible", even if being hidden before.

**Comment by ColdHeat** [comment]
Good point. Looks like this issue is here: https://github.com/CTFd/ctfcli/blob/720b3657fb516ab2faaaff8348ba45f3f608aa8b/ctfcli/utils/challenge.py#L143

It should probably copy the visibility state from the original challenge data. We should also probably have a visibility or state construct in `challenge.yml`.
